name: airport-recommendation-env

dependencies:
  - python=3.9.18
  - pip
  - pip:
      - notebook==7.1.1
      - numpy==1.26.4
      - scikit-learn==1.3.2
      - pandas==2.0.3
      - matplotlib==3.7.5
      - mlflow==2.11.1
      - xgboost==2.0.3
